version: 0.2

phases:
  pre_build:
    commands:
      - echo $CODEBUILD_WEBHOOK_TRIGGER
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 593204228656.dkr.ecr.us-east-2.amazonaws.com
      - docker image ls
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...  
      #- codebuild-breakpoint
      - aws ecr get-login-password --region us-west-1 | docker login --username AWS --password-stdin 593204228656.dkr.ecr.us-west-1.amazonaws.com
      - docker build -t bootcamp-demo-repo .
      #- docker tag image_from_another_account:latest 461693547282.dkr.ecr.us-west-2.amazonaws.com/image_from_another_account:latest
      - docker tag bootcamp-demo-repo:latest 593204228656.dkr.ecr.us-west-1.amazonaws.com/bootcamp-demo-repo:latest
      - docker push 593204228656.dkr.ecr.us-west-1.amazonaws.com/bootcamp-demo-repo:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
